version: '3.8'
services:
  wordpress:
    build:
      context: .
    image: ${IMAGE_REPO_NAME}:${IMAGE_TAG}
    environment:
      WORDPRESS_DB_HOST: 'database-2-instance-1.czsu0y4s8anw.us-east-2.rds.amazonaws.com'
      WORDPRESS_DB_USER: 'admin'
      WORDPRESS_DB_PASSWORD: 'Hansol00!'
      WORDPRESS_DB_NAME: 'wordpress'
    ports:
      - '80:80'
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress: